import type { Destination } from '@rasikh/shared';
import type { AgentAction, Locale } from '@/domain/types';

const en = {
  intro: 'Review the next decision and follow the activity recorded for your move.',
  noApprovals: 'No decisions waiting for you',
  noApprovalsHint: 'New requests appear here when a draft or an offer needs your review.',
  noHire: 'No newcomer case yet',
  noHireHint: 'Add a hire from the employer view to begin the newcomer journey.',
  openEmployer: 'Open employer view',
  rentalTitle: 'Review rental application',
  bankTitle: 'Review account application',
  termsTitle: 'Review offered terms',
  recipient: 'Recipient',
  property: 'Home',
  unit: 'Unit {unit}',
  studio: 'Studio',
  bedrooms: 'Bedrooms: {count}',
  rent: 'Estimated annual rent',
  chequeOptions: 'Property accepts {count} cheques',
  offeredCheques: 'Offered payment schedule: {count} cheques',
  backing: 'Employer backing on this application',
  backingYes: 'Attached · {employer}',
  backingNo: 'Not attached',
  backingChanged:
    'Your employer’s current backing differs from this application record. Review it before deciding.',
  disclosures: 'Draft contents',
  raw: 'Document or details',
  derived: 'Derived result only',
  allow: 'Allowed by the demo policy',
  consentOn: 'Current consent: on',
  consentOff: 'Current consent: off',
  consentSwitch: 'Allow {label} for {destination}',
  consentScope:
    'This consent applies to all {destination} in your trust passport, including this recipient. It does not submit the draft.',
  derivedRule: 'Only a derived result is permitted',
  forbidden: 'This disclosure is not permitted by the demo policy',
  invalidDerived: 'This draft contains raw details where only a derived result is permitted.',
  consentNeeded: 'Turn on the required consent to approve this draft.',
  policyBlocked: 'This draft needs to be corrected before approval.',
  draftMissing: 'The matching draft or recipient is unavailable. Approval is disabled.',
  termsMissing: 'The current offer is unavailable. Acceptance is disabled.',
  simulation:
    'Approving records a simulated submission in Rasikh. No external application is sent.',
  termsSimulation:
    'Accepting records the offered terms in this demo. No lease is signed and no external message is sent.',
  approveDemo: 'Approve demo submission',
  acceptTerms: 'Accept demo terms',
  decline: 'Decline draft',
  declineTerms: 'Decline terms',
  savedApproval: 'Your decision was saved.',
  savedConsent: 'Your consent setting was saved.',
  savedTerms: 'The demo terms were accepted.',
  saveError: 'The change could not be saved. Check the current draft and consent, then try again.',
  originalError: 'Original response',
  originalNote: 'Original recorded note',
  originalSummary: 'Original activity text (demo record)',
  offerNote: 'Original offer note',
  approvalHistory: 'Your decisions',
  approved: 'Approved',
  declined: 'Declined',
  newestFirst: 'Newest first · recorded activity',
  historyHint:
    'Each status describes the event when it was recorded. Live document extraction is labelled separately.',
  recordedFor: 'Step: {step}',
  roadmapSummary: 'Demo roadmap recorded',
  roadmapReason:
    'The roadmap orders the recorded steps by their dependencies. Review your next action on the Roadmap tab.',
  documentSummary: 'Demo document review recorded',
  documentFor: 'Demo review: {documents}',
  documentReason:
    'This entry records demo extraction or review. Open Documents to inspect the fields and verification status.',
  documentRecorded: 'Document extraction recorded',
  documentRecordedReason:
    'Open Documents to inspect the recorded fields and extraction source. Historical activity alone does not establish how the current document was extracted.',
  liveDocument: 'Vertex AI extraction: {document}',
  liveDocumentReason:
    'The matching document record identifies Vertex AI as its extraction source. Review, correct and confirm the extracted values in Documents.',
  documentConfirmed: 'Document fields confirmed: {document}',
  documentRejected: 'Document fields rejected: {document}',
  documentReviewReason:
    'Your review was recorded in Rasikh. The original extraction source and upload time are retained.',
  liveTitle: 'Explain my next step',
  liveHint:
    'Request a Vertex AI explanation of this case’s current roadmap and approval status. The explanation does not submit an application or change your records.',
  liveChecking: 'Checking live explanation availability…',
  liveUnavailable: 'Live explanation is unavailable.',
  liveAvailable: 'Live explanation is available through Vertex AI.',
  liveRefresh: 'Check availability',
  liveAsk: 'Explain my next step',
  liveResult: 'Live Vertex AI explanation',
  liveNext: 'Suggested next action',
  liveWhy: 'Why this action',
  liveApproval: 'This suggestion needs your approval before you act.',
  liveDisclosures: 'Sharing notes',
  sharingNote: '{label} · {destination}: {permission}{derived}',
  sharingPermitted: 'currently permitted',
  sharingWithheld: 'withheld until approved',
  sharingDerived: ' · derived result only',
  liveError:
    'The live explanation could not be completed. No explanation was substituted and no records were changed.',
  liveStale:
    'Your records have changed since this explanation was requested. Request a new explanation for the current state.',
  documentRequestedSummary: 'Document request recorded',
  documentRequestedReason: 'Review the request and add the relevant document on the Documents tab.',
  approvalSummary: 'Decision requested',
  approvalFor: 'Review requested for {recipient}',
  approvalReason:
    'Review the recipient, draft contents, employer backing and current consent before deciding.',
  submittedSummary: 'Demo application submission recorded',
  submittedFor: 'Demo application recorded for {recipient}',
  submittedReason:
    'This is a simulated submission in Rasikh after approval. It does not confirm any external delivery.',
  tammSummary: 'Demo government application status recorded',
  tammFor: 'Demo status recorded: {step}',
  tammReason:
    'Government application activity is simulated here. This entry does not confirm a live TAMM submission.',
  decisionSummary: 'Demo application decision recorded',
  decisionFor: '{recipient}: {outcome}',
  decisionReason:
    'A decision was recorded in the demo. Review any offered terms or requests for information before continuing.',
  notificationSummary: 'Demo employer notification recorded',
  notificationReason:
    'This entry records a simulated employer update. No email or other external message was sent.',
  updateSummary: 'Demo progress update recorded',
  updateReason: 'This entry records a change to the roadmap or employer backing in Rasikh.',
  declinedSummary: 'Draft declined',
  declinedReason: 'You declined the draft. No simulated submission was made for this request.',
  blockedSummary: 'Sharing restriction recorded',
  blockedReason:
    'Review the recorded restriction and your current consent. This demo entry does not verify live enforcement.',
  termsAcceptedSummary: 'Demo terms accepted',
  termsAcceptedReason:
    'You accepted the offered terms in Rasikh’s demo. This records a decision without signing a lease or sending a message.',
  outcomeApproved: 'Approved',
  outcomeInfo: 'More information requested',
  outcomeTerms: 'Different terms offered',
  outcomeDeclined: 'Declined',
  destinationLandlord: 'landlords',
  destinationBank: 'banks',
  destinationEmployer: 'your employer',
  destinationSchool: 'schools',
  destinationTamm: 'government services',
  destinationLlm: 'the AI provider',
  destinationNewcomer: 'you',
  readyToDecide: 'Ready to approve',
  consentFirst: 'Consent needed first',
  needsFix: 'Needs a correction',
  sharedWith: 'Shared with {recipient}',
  kindRental: 'Rental application',
  kindBank: 'Bank account application',
  kindTerms: 'Offered terms',
} as const;

type Key = keyof typeof en;
const ar: Record<Key, string> = {
  intro: 'راجع القرار التالي وتابع الأنشطة المسجّلة لانتقالك.',
  noApprovals: 'لا توجد قرارات بانتظارك',
  noApprovalsHint: 'تظهر الطلبات الجديدة هنا عندما تحتاج مسودة أو عرض إلى مراجعتك.',
  noHire: 'لا توجد حالة انتقال بعد',
  noHireHint: 'أضف موظفًا من واجهة جهة العمل لبدء رحلة الاستقرار.',
  openEmployer: 'فتح واجهة جهة العمل',
  rentalTitle: 'مراجعة طلب الإيجار',
  bankTitle: 'مراجعة طلب الحساب',
  termsTitle: 'مراجعة الشروط المعروضة',
  recipient: 'الجهة المستلمة',
  property: 'المسكن',
  unit: 'الوحدة {unit}',
  studio: 'استوديو',
  bedrooms: 'غرف النوم: {count}',
  rent: 'الإيجار السنوي التقديري',
  chequeOptions: 'عدد الشيكات المقبول للعقار: {count}',
  offeredCheques: 'عدد الشيكات في العرض: {count}',
  backing: 'دعم جهة العمل في هذا الطلب',
  backingYes: 'مرفق · {employer}',
  backingNo: 'غير مرفق',
  backingChanged: 'يختلف دعم جهة العمل الحالي عن سجل هذا الطلب. راجعه قبل اتخاذ القرار.',
  disclosures: 'محتويات المسودة',
  raw: 'المستند أو التفاصيل',
  derived: 'نتيجة مستخلصة فقط',
  allow: 'مسموح وفق سياسة العرض التجريبي',
  consentOn: 'الموافقة الحالية: مفعّلة',
  consentOff: 'الموافقة الحالية: غير مفعّلة',
  consentSwitch: 'السماح بمشاركة {label} مع {destination}',
  consentScope:
    'تسري هذه الموافقة على جميع الجهات ضمن فئة «{destination}» في جواز الثقة، بما فيها هذه الجهة. ولا تقدّم المسودة.',
  derivedRule: 'المسموح هو نتيجة مستخلصة فقط',
  forbidden: 'لا تسمح سياسة العرض التجريبي بهذه المشاركة',
  invalidDerived: 'تتضمن المسودة تفاصيل أصلية، بينما المسموح هو نتيجة مستخلصة فقط.',
  consentNeeded: 'فعّل الموافقة المطلوبة قبل اعتماد هذه المسودة.',
  policyBlocked: 'يجب تصحيح هذه المسودة قبل اعتمادها.',
  draftMissing: 'المسودة المطابقة أو الجهة المستلمة غير متاحة. لا يمكن اعتماد الطلب.',
  termsMissing: 'العرض الحالي غير متاح. لا يمكن قبول الشروط.',
  simulation: 'يسجّل الاعتماد تقديمًا محاكى داخل راسخ. لا يُرسل أي طلب إلى جهة خارجية.',
  termsSimulation:
    'يسجّل القبول الشروط المعروضة في النسخة التجريبية. لا يُوقّع عقد ولا تُرسل رسالة خارجية.',
  approveDemo: 'اعتماد التقديم التجريبي',
  acceptTerms: 'قبول الشروط التجريبية',
  decline: 'رفض المسودة',
  declineTerms: 'رفض الشروط',
  savedApproval: 'حُفظ قرارك.',
  savedConsent: 'حُفظ إعداد الموافقة.',
  savedTerms: 'قُبلت الشروط التجريبية.',
  saveError: 'تعذّر حفظ التغيير. راجع المسودة والموافقات الحالية ثم حاول مجددًا.',
  originalError: 'الرد الأصلي',
  originalNote: 'الملاحظة المسجّلة بلغتها الأصلية',
  originalSummary: 'نص النشاط بلغته الأصلية (سجل تجريبي)',
  offerNote: 'ملاحظة العرض بلغتها الأصلية',
  approvalHistory: 'قراراتك',
  approved: 'معتمد',
  declined: 'مرفوض',
  newestFirst: 'الأحدث أولًا · الأنشطة المسجّلة',
  historyHint: 'تصف كل حالة النشاط وقت تسجيله. يُميّز الاستخراج الفعلي للمستندات بشكل منفصل.',
  recordedFor: 'الخطوة: {step}',
  roadmapSummary: 'سُجّلت خريطة انتقال تجريبية',
  roadmapReason:
    'ترتّب الخريطة الخطوات المسجّلة وفق اعتماد كل خطوة على سابقتها. راجع الإجراء التالي في تبويب خريطة الانتقال.',
  documentSummary: 'سُجّلت مراجعة تجريبية للمستندات',
  documentFor: 'مراجعة تجريبية: {documents}',
  documentReason:
    'يسجّل هذا النشاط استخراجًا أو مراجعة تجريبية. افتح المستندات لفحص الحقول وحالة التحقق.',
  documentRecorded: 'سُجّل استخراج بيانات مستند',
  documentRecordedReason:
    'افتح المستندات لفحص الحقول المسجّلة ومصدر الاستخراج. لا يثبت سجل النشاط وحده كيفية استخراج المستند الحالي.',
  liveDocument: 'استخراج عبر Vertex AI: {document}',
  liveDocumentReason:
    'يحدّد سجل المستند المطابق Vertex AI مصدرًا للاستخراج. راجع القيم المستخرجة وصحّحها وأكّدها من تبويب المستندات.',
  documentConfirmed: 'أُكّدت حقول المستند: {document}',
  documentRejected: 'رُفضت حقول المستند: {document}',
  documentReviewReason: 'سُجّلت مراجعتك داخل راسخ مع الاحتفاظ بمصدر الاستخراج ووقت الرفع الأصليين.',
  liveTitle: 'شرح الخطوة التالية',
  liveHint:
    'اطلب من Vertex AI شرح خريطة انتقال هذه الحالة وحالة موافقاتها الحالية. لا يقدّم الشرح أي طلب ولا يغيّر سجلاتك.',
  liveChecking: 'جارٍ التحقق من توفر الشرح الفعلي…',
  liveUnavailable: 'الشرح الفعلي غير متاح.',
  liveAvailable: 'الشرح الفعلي متاح عبر Vertex AI.',
  liveRefresh: 'التحقق من التوفر',
  liveAsk: 'شرح الخطوة التالية',
  liveResult: 'شرح فعلي عبر Vertex AI',
  liveNext: 'الإجراء التالي المقترح',
  liveWhy: 'سبب اقتراح الإجراء',
  liveApproval: 'يتطلب هذا الاقتراح موافقتك قبل التنفيذ.',
  liveDisclosures: 'ملاحظات المشاركة',
  sharingNote: '{label} · {destination}: {permission}{derived}',
  sharingPermitted: 'مسموح حاليًا',
  sharingWithheld: 'محجوب حتى الموافقة',
  sharingDerived: ' · نتيجة مستخلصة فقط',
  liveError: 'تعذّر إكمال الشرح الفعلي. لم يُستبدل بشرح آخر ولم تتغير سجلاتك.',
  liveStale: 'تغيّرت سجلاتك منذ طلب هذا الشرح. اطلب شرحًا جديدًا للحالة الحالية.',
  documentRequestedSummary: 'سُجّل طلب مستند',
  documentRequestedReason: 'راجع الطلب وأضف المستند المطلوب من تبويب المستندات.',
  approvalSummary: 'طُلب قرارك',
  approvalFor: 'مراجعة مطلوبة لطلب موجّه إلى {recipient}',
  approvalReason:
    'راجع الجهة المستلمة ومحتويات المسودة ودعم جهة العمل وموافقاتك الحالية قبل القرار.',
  submittedSummary: 'سُجّل تقديم تجريبي لطلب',
  submittedFor: 'سُجّل طلب تجريبي موجّه إلى {recipient}',
  submittedReason: 'هذا تقديم محاكى داخل راسخ بعد الاعتماد، ولا يؤكّد وصول أي طلب إلى جهة خارجية.',
  tammSummary: 'سُجّلت حالة تجريبية لطلب حكومي',
  tammFor: 'سُجّلت حالة تجريبية: {step}',
  tammReason: 'أنشطة الطلبات الحكومية هنا محاكاة. لا يؤكّد هذا السجل تقديمًا فعليًا عبر تم.',
  decisionSummary: 'سُجّل قرار تجريبي بشأن طلب',
  decisionFor: '{recipient}: {outcome}',
  decisionReason:
    'سُجّل قرار في النسخة التجريبية. راجع الشروط المعروضة أو طلبات المعلومات قبل المتابعة.',
  notificationSummary: 'سُجّل إشعار تجريبي لجهة العمل',
  notificationReason:
    'يسجّل هذا النشاط تحديثًا محاكى لجهة العمل. لم تُرسل رسالة بريد أو أي رسالة خارجية.',
  updateSummary: 'سُجّل تحديث للتقدم التجريبي',
  updateReason: 'يسجّل هذا النشاط تغييرًا في خريطة الانتقال أو دعم جهة العمل داخل راسخ.',
  declinedSummary: 'رُفضت المسودة',
  declinedReason: 'رفضت المسودة، لذلك لم يُسجّل تقديم تجريبي لهذا الطلب.',
  blockedSummary: 'سُجّل قيد على المشاركة',
  blockedReason:
    'راجع القيد المسجّل وموافقاتك الحالية. لا يثبت هذا السجل التجريبي إنفاذًا فعليًا للسياسة.',
  termsAcceptedSummary: 'قُبلت الشروط التجريبية',
  termsAcceptedReason:
    'قبلت الشروط المعروضة في نسخة راسخ التجريبية. يسجّل ذلك قرارًا دون توقيع عقد أو إرسال رسالة.',
  outcomeApproved: 'معتمد',
  outcomeInfo: 'معلومات إضافية مطلوبة',
  outcomeTerms: 'شروط بديلة معروضة',
  outcomeDeclined: 'مرفوض',
  destinationLandlord: 'الملاك',
  destinationBank: 'البنوك',
  destinationEmployer: 'جهة عملك',
  destinationSchool: 'المدارس',
  destinationTamm: 'الخدمات الحكومية',
  destinationLlm: 'مزوّد الذكاء الاصطناعي',
  destinationNewcomer: 'أنت',
  readyToDecide: 'جاهزة للاعتماد',
  consentFirst: 'تلزم الموافقة أولًا',
  needsFix: 'تحتاج إلى تصحيح',
  sharedWith: 'تُشارك مع {recipient}',
  kindRental: 'طلب إيجار',
  kindBank: 'طلب فتح حساب',
  kindTerms: 'شروط معروضة',
};

export function agentText(
  locale: Locale,
  key: Key,
  values: Record<string, string | number> = {},
): string {
  return Object.entries(values).reduce(
    (message, [name, value]) => message.replaceAll(`{${name}}`, String(value)),
    (locale === 'ar' ? ar : en)[key] as string,
  );
}

const DESTINATION_KEYS: Record<Destination, Key> = {
  landlord: 'destinationLandlord',
  bank: 'destinationBank',
  employer: 'destinationEmployer',
  school: 'destinationSchool',
  tamm: 'destinationTamm',
  llm_provider: 'destinationLlm',
  newcomer: 'destinationNewcomer',
};

export function destinationText(locale: Locale, destination: Destination): string {
  return agentText(locale, DESTINATION_KEYS[destination]);
}

export const EVENT_COPY: Record<AgentAction['kind'], [Key, Key]> = {
  roadmap_generated: ['roadmapSummary', 'roadmapReason'],
  document_extracted: ['documentSummary', 'documentReason'],
  document_requested: ['documentRequestedSummary', 'documentRequestedReason'],
  approval_requested: ['approvalSummary', 'approvalReason'],
  application_submitted: ['submittedSummary', 'submittedReason'],
  tamm_application: ['tammSummary', 'tammReason'],
  decision_received: ['decisionSummary', 'decisionReason'],
  employer_notified: ['notificationSummary', 'notificationReason'],
  step_updated: ['updateSummary', 'updateReason'],
  guard_blocked: ['blockedSummary', 'blockedReason'],
};

/** Historical prose is retained separately. These are known demo-generated legacy notes. */
export function knownDemoNote(value: string): boolean {
  return /^(You approved it,|Nothing is sent until you approve\.|The next steps that depended|You declined, so|Your family of four needs|Documents were verified, so|The visa was issued today,|The lease was signed and|Your Emirates ID application is in,|The last application was approved,|Name, dates and role agree|Names, dates and role agree|Employer backing is recorded|Open applications now show)/.test(
    value,
  );
}
