import type { DataLabel } from '@rasikh/shared';
import type { CaseInput, Journey, ResultBase } from './types.js';

export interface SimulationRange {
  min: number;
  max: number;
  illustrative: true;
  rationale: string;
}
export interface SimulationNumber {
  value: number;
  illustrative: true;
  rationale: string;
}
export interface SimulationPolicy {
  parallel_steps: boolean;
  proactive_documents: boolean;
  notice_days: SimulationRange;
  handoff_days: SimulationRange;
  illustrative: true;
  rationale: string;
}
export interface SimulationAssumptions {
  illustrative: true;
  rationale: string;
  default_seed: SimulationNumber;
  default_runs: SimulationNumber;
  maximum_runs: SimulationNumber;
  sensitivity_relative_change: SimulationNumber;
  step_duration_days: Record<string, SimulationRange>;
  document_preparation_days: Partial<Record<DataLabel, SimulationRange>>;
  /** Synthetic model of documents generated by earlier milestones; not legal prerequisites. */
  document_producers: Partial<Record<DataLabel, string>>;
  delay_probability: SimulationNumber;
  unexpected_delay_days: SimulationRange;
  baseline: SimulationPolicy;
  orchestration: SimulationPolicy;
}
export interface SimulationOptions {
  seed?: number;
  runs?: number;
  cases?: readonly CaseInput[];
  assumptions?: SimulationAssumptions;
  include_sensitivity?: boolean;
}
export interface DaysDistribution {
  samples_days: number[];
  median: number;
  p10: number;
  p90: number;
  min: number;
  max: number;
}
export interface SimulationCaseResult {
  case_id: string;
  journey: Journey;
  target_step_id: string;
  baseline_days: DaysDistribution;
  orchestrated_days: DaysDistribution;
  /** Paired per-run differences, not a difference between independent cohorts. */
  days_saved: DaysDistribution;
}
export type SensitivityParameter =
  | 'processing_duration'
  | 'delay_probability'
  | 'delay_severity'
  | 'document_preparation'
  | 'baseline_notice'
  | 'baseline_handoff'
  | 'orchestrated_notice'
  | 'orchestrated_handoff'
  | 'parallel_steps'
  | 'proactive_documents';
export interface SimulationSensitivity {
  parameter: SensitivityParameter;
  low_setting: number | boolean;
  high_setting: number | boolean;
  case_id: string;
  low_median_saved_days: number;
  high_median_saved_days: number;
  median_saved_span_days: number;
}
export interface SimulationResult extends ResultBase {
  evidence_scope: 'illustrative_simulation';
  measured_real_world: false;
  seed: number;
  runs: number;
  randomness: 'common_random_numbers_per_step_and_document';
  assumptions: SimulationAssumptions;
  inputs: CaseInput[];
  cases: SimulationCaseResult[];
  sensitivity: SimulationSensitivity[];
}
