// src/shared/failureCodes.ts
export const Failure = {
  TARGET_NOT_FOUND: "TARGET_NOT_FOUND",
  ACTION_NOT_ALLOWED: "ACTION_NOT_ALLOWED",
  CONTENT_SCRIPT_UNAVAILABLE: "CONTENT_SCRIPT_UNAVAILABLE",
  PERCEPTION_FAILED: "PERCEPTION_FAILED",
  NO_SITE_GRANT: "NO_SITE_GRANT",
  NETWORK_ERROR: "NETWORK_ERROR",
  VALIDATION_REJECTED: "VALIDATION_REJECTED"
} as const;
export type FailureCode = keyof typeof Failure;
